server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/chandrakantjadhav1401-tech/Microservices-Config-Server
          clone-on-start: true